# Generated by Django 2.1.2 on 2018-11-23 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbxResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('data', models.FileField(upload_to='audio/')),
                ('role', models.CharField(choices=[('R', 'reference'), ('A', 'anchor'), ('S', 'stimulus')], default='S', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MosLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MosResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='kowhowse.MosLevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MushraResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MushraResponseBit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mushraresponsebits', to='kowhowse.Audio')),
                ('whole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bits', to='kowhowse.MushraResponse')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('next_page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='kowhowse.Page')),
                ('prev_page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='kowhowse.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('instruction', models.FileField(upload_to='text/')),
                ('species', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('instruction', models.FileField(upload_to='text/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('instruction', models.FileField(upload_to='text/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kowhowse.Feed')),
                ('seed', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('kowhowse.feed',),
        ),
        migrations.CreateModel(
            name='AbQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kowhowse.Question')),
            ],
            options={
                'abstract': False,
            },
            bases=('kowhowse.question',),
        ),
        migrations.CreateModel(
            name='AbxFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kowhowse.Feed')),
                ('seed', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('kowhowse.feed',),
        ),
        migrations.CreateModel(
            name='AbxQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kowhowse.Question')),
            ],
            options={
                'abstract': False,
            },
            bases=('kowhowse.question',),
        ),
        migrations.CreateModel(
            name='MosFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kowhowse.Feed')),
                ('seed', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('kowhowse.feed',),
        ),
        migrations.CreateModel(
            name='MosQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kowhowse.Question')),
                ('levels', models.ManyToManyField(related_name='mosquestions', to='kowhowse.MosLevel')),
            ],
            options={
                'abstract': False,
            },
            bases=('kowhowse.question',),
        ),
        migrations.CreateModel(
            name='MushraFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kowhowse.Feed')),
                ('seed', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('kowhowse.feed',),
        ),
        migrations.CreateModel(
            name='MushraQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kowhowse.Question')),
                ('num_anchors', models.PositiveIntegerField(null=True)),
                ('num_stimuli', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('kowhowse.question',),
        ),
        migrations.CreateModel(
            name='NullFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kowhowse.Feed')),
            ],
            bases=('kowhowse.feed',),
        ),
        migrations.CreateModel(
            name='SectionFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kowhowse.Feed')),
            ],
            bases=('kowhowse.feed',),
        ),
        migrations.AddField(
            model_name='subject',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='kowhowse.Survey'),
        ),
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='kowhowse.Survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='samples',
            field=models.ManyToManyField(related_name='questions', to='kowhowse.Audio'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kowhowse.Section'),
        ),
        migrations.AddField(
            model_name='page',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='kowhowse.Subject'),
        ),
        migrations.AddField(
            model_name='page',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='kowhowse.Survey'),
        ),
        migrations.AddField(
            model_name='feed',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='kowhowse.Page'),
        ),
        migrations.AddField(
            model_name='audio',
            name='system',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='kowhowse.System'),
        ),
        migrations.AddField(
            model_name='abxresponse',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abxresponses', to='kowhowse.Audio'),
        ),
        migrations.AddField(
            model_name='abresponse',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abresponses', to='kowhowse.Audio'),
        ),
        migrations.AddField(
            model_name='sectionfeed',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='kowhowse.Section'),
        ),
        migrations.AddField(
            model_name='mushraresponse',
            name='feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='kowhowse.MushraFeed'),
        ),
        migrations.AddField(
            model_name='mushrafeed',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='kowhowse.MushraQuestion'),
        ),
        migrations.AddField(
            model_name='mushrafeed',
            name='samples',
            field=models.ManyToManyField(related_name='mushrafeeds', to='kowhowse.Audio'),
        ),
        migrations.AddField(
            model_name='mosresponse',
            name='feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='kowhowse.MosFeed'),
        ),
        migrations.AddField(
            model_name='mosfeed',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='kowhowse.MosQuestion'),
        ),
        migrations.AddField(
            model_name='mosfeed',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mos_feeds', to='kowhowse.Audio'),
        ),
        migrations.AddField(
            model_name='abxresponse',
            name='feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='kowhowse.AbxFeed'),
        ),
        migrations.AddField(
            model_name='abxfeed',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='kowhowse.AbxQuestion'),
        ),
        migrations.AddField(
            model_name='abxfeed',
            name='samples',
            field=models.ManyToManyField(related_name='abxfeeds', to='kowhowse.Audio'),
        ),
        migrations.AddField(
            model_name='abresponse',
            name='feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='kowhowse.AbFeed'),
        ),
        migrations.AddField(
            model_name='abfeed',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='kowhowse.AbQuestion'),
        ),
        migrations.AddField(
            model_name='abfeed',
            name='samples',
            field=models.ManyToManyField(related_name='abfeeds', to='kowhowse.Audio'),
        ),
    ]
