# Generated by Django 2.0.7 on 2018-09-04 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbxResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('data', models.FileField(upload_to='audio/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MosResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MushraResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MushraResponseBit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mushraresponsebits', to='survey.Audio')),
                ('whole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bits', to='survey.MushraResponse')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('next_page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='survey.Page')),
                ('prev_page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='survey.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('instruction', models.FileField(upload_to='text/')),
                ('species', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('instruction', models.FileField(upload_to='text/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('instruction', models.FileField(upload_to='text/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Feed')),
                ('code', models.IntegerField(choices=[(0, 'AB'), (1, 'BA')], default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.feed',),
        ),
        migrations.CreateModel(
            name='AbQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Question')),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.question',),
        ),
        migrations.CreateModel(
            name='AbxFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Feed')),
                ('seed', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.feed',),
        ),
        migrations.CreateModel(
            name='AbxQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Question')),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.question',),
        ),
        migrations.CreateModel(
            name='MosFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Feed')),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.feed',),
        ),
        migrations.CreateModel(
            name='MosQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Question')),
                ('num_levels', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.question',),
        ),
        migrations.CreateModel(
            name='MushraFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Feed')),
                ('seed', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.feed',),
        ),
        migrations.CreateModel(
            name='MushraQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Question')),
                ('num_choices', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('survey.question',),
        ),
        migrations.CreateModel(
            name='NullFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Feed')),
            ],
            bases=('survey.feed',),
        ),
        migrations.CreateModel(
            name='SectionFeed',
            fields=[
                ('feed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.Feed')),
            ],
            bases=('survey.feed',),
        ),
        migrations.AddField(
            model_name='subject',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='samples',
            field=models.ManyToManyField(related_name='questions', to='survey.Audio'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.Section'),
        ),
        migrations.AddField(
            model_name='page',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='survey.Subject'),
        ),
        migrations.AddField(
            model_name='page',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='feed',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='survey.Page'),
        ),
        migrations.AddField(
            model_name='audio',
            name='system',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='survey.System'),
        ),
        migrations.AddField(
            model_name='abxresponse',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abxresponses', to='survey.Audio'),
        ),
        migrations.AddField(
            model_name='abresponse',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abresponses', to='survey.Audio'),
        ),
        migrations.AddField(
            model_name='sectionfeed',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='survey.Section'),
        ),
        migrations.AddField(
            model_name='mushraresponse',
            name='feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='survey.MushraFeed'),
        ),
        migrations.AddField(
            model_name='mushrafeed',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='survey.MushraQuestion'),
        ),
        migrations.AddField(
            model_name='mushrafeed',
            name='samples',
            field=models.ManyToManyField(related_name='mushrafeeds', to='survey.Audio'),
        ),
        migrations.AddField(
            model_name='mosresponse',
            name='feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='survey.MosFeed'),
        ),
        migrations.AddField(
            model_name='mosfeed',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='survey.MosQuestion'),
        ),
        migrations.AddField(
            model_name='mosfeed',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mos_feeds', to='survey.Audio'),
        ),
        migrations.AddField(
            model_name='abxresponse',
            name='feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='survey.AbxFeed'),
        ),
        migrations.AddField(
            model_name='abxfeed',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='survey.AbxQuestion'),
        ),
        migrations.AddField(
            model_name='abxfeed',
            name='samples',
            field=models.ManyToManyField(related_name='abxfeeds', to='survey.Audio'),
        ),
        migrations.AddField(
            model_name='abresponse',
            name='feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='survey.AbFeed'),
        ),
        migrations.AddField(
            model_name='abfeed',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='survey.AbQuestion'),
        ),
        migrations.AddField(
            model_name='abfeed',
            name='samples',
            field=models.ManyToManyField(related_name='abfeeds', to='survey.Audio'),
        ),
    ]
